server:
  port: 9004

spring:
  application:
    name: service-message

  profiles:
    include: common_dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

  instance:
    instance-id: 消息服务-9004
    prefer-ip-address: true

info:
  author.name: trevor
  app.name: general
  server.port: ${server.port}
  application.name: ${spring.application.name}

